package drillsim.clients;

/*
 * gui.java
 *
 * Created on March 1, 2006, 1:08 AM
 */

import java.net.*;
import javax.swing.*;
import java.awt.*;
import java.io.*;

/**
 *
 * @author  Thomas Cgui
 */
public class Gui extends javax.swing.JFrame {
    
    private boolean thingsToAddVisibility = false;
    private int layerNumber = -1;
    private GeoInterface ginterface = new GeoInterface("tchen3", "69Weiaid");
    private Socket socket = null;
    Client2DInput c = null;
    
    /** Creates new foguigui */
    public Gui() {
        initComponents();

        try
        {
            socket = new Socket("128.195.185.30", 4444);
        }
        catch (UnknownHostException e)
        {
        }
        catch (IOException e)
        {
        }
        c = new Client2DInput(socket); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        LeftPanel = new javax.swing.JPanel();
        LayerPanel = new javax.swing.JPanel();
        LayerList = new javax.swing.JList();
        LayerActions = new javax.swing.JPanel();
        AddLayer = new javax.swing.JButton();
        DeleteLayer = new JButton(new DeleteLayerAction());
        InputPanel = new javax.swing.JPanel();
        temp = new javax.swing.JTextArea();
        ThingsToAdd = new javax.swing.JInternalFrame();
        ThingsToAddPanel = new javax.swing.JPanel();
        AddCrisis = new javax.swing.JButton();
        AddObstacle = new javax.swing.JButton();
        AddPeople = new javax.swing.JButton();
        AddEntry = new javax.swing.JButton();
        AddResource = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        NewScenario = new javax.swing.JMenuItem();
        LoadScenario = new javax.swing.JMenuItem();
        SaveScenario = new javax.swing.JMenuItem();
        CloseScenario = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        View = new javax.swing.JMenu();
        Tools = new javax.swing.JMenu();
        Layers = new javax.swing.JMenu();
        Window = new javax.swing.JMenu();
        Help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        LeftPanel.setLayout(new java.awt.BorderLayout());

        LeftPanel.setBorder(new javax.swing.border.TitledBorder("Layers"));
        LeftPanel.setPreferredSize(new java.awt.Dimension(150, 500));
        LayerPanel.setLayout(new java.awt.BorderLayout());

        LayerList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Crisis", "Obstacle", "People", "Entry", "Resource" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        LayerPanel.add(LayerList, java.awt.BorderLayout.CENTER);

        LeftPanel.add(LayerPanel, java.awt.BorderLayout.CENTER);

        AddLayer.setText("Add");
        AddLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLayerActionPerformed(evt);
            }
        });

        LayerActions.add(AddLayer);

        DeleteLayer.setText("Delete");
        DeleteLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLayerActionPerformed(evt);
            }
        });

        LayerActions.add(DeleteLayer);

        LeftPanel.add(LayerActions, java.awt.BorderLayout.SOUTH);

        getContentPane().add(LeftPanel, java.awt.BorderLayout.WEST);

        InputPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        InputPanel.add(c);
        temp.setText(" This is where the input goes");
        InputPanel.add(temp);

        ThingsToAdd.setPreferredSize(new java.awt.Dimension(100, 200));
        ThingsToAdd.setVisible(thingsToAddVisibility);
        ThingsToAddPanel.setLayout(new java.awt.GridLayout(5, 1));

        AddCrisis.setText("Add Crisis");
        AddCrisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCrisisActionPerformed(evt);
            }
        });

        ThingsToAddPanel.add(AddCrisis);

        AddObstacle.setText("Add Obstacle");
        ThingsToAddPanel.add(AddObstacle);

        AddPeople.setText("Add People");
        ThingsToAddPanel.add(AddPeople);

        AddEntry.setText("Add Entry");
        ThingsToAddPanel.add(AddEntry);

        AddResource.setText("Add Resource");
        ThingsToAddPanel.add(AddResource);

        ThingsToAdd.getContentPane().add(ThingsToAddPanel, java.awt.BorderLayout.CENTER);

        InputPanel.add(ThingsToAdd);

        getContentPane().add(InputPanel, java.awt.BorderLayout.CENTER);

        File.setText("File");
        NewScenario.setText("New Scenario");
        NewScenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewScenarioActionPerformed(evt);
            }
        });

        File.add(NewScenario);

        LoadScenario.setText("Load Scenario");
        File.add(LoadScenario);

        SaveScenario.setText("Save Scenario");
        SaveScenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveScenarioActionPerformed(evt);
            }
        });

        File.add(SaveScenario);

        CloseScenario.setText("Close Scenario");
        File.add(CloseScenario);

        Exit.setText("Exit");
        File.add(Exit);

        MenuBar.add(File);

        Edit.setText("Edit");
        Edit.setEnabled(false);
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        MenuBar.add(Edit);

        View.setText("View");
        View.setEnabled(false);
        MenuBar.add(View);

        Tools.setText("Tools");
        Tools.setEnabled(false);
        MenuBar.add(Tools);

        Layers.setText("Layers");
        Layers.setEnabled(false);
        Layers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LayersActionPerformed(evt);
            }
        });

        MenuBar.add(Layers);

        Window.setText("Window");
        Window.setEnabled(false);
        MenuBar.add(Window);

        Help.setText("Help");
        Help.setEnabled(false);
        MenuBar.add(Help);

        setJMenuBar(MenuBar);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void AddCrisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCrisisActionPerformed
// TODO add your handling code here:
        
        
    }//GEN-LAST:event_AddCrisisActionPerformed

    private void SaveScenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveScenarioActionPerformed
// TODO add your handling code here:
        // delete all entries with same layer_id in DB
        // rewrite everything that's currently in the layers
        c.commitToDB();
    }//GEN-LAST:event_SaveScenarioActionPerformed

    private void NewScenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewScenarioActionPerformed
// TODO add your handling code here:
        // check that there's not current layer ID continue
        int saveId = ginterface.getSaveId();
        if (saveId == -1)
            layerNumber = 0;
        else
            layerNumber = saveId++;
    }//GEN-LAST:event_NewScenarioActionPerformed

    private void DeleteLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLayerActionPerformed
// TODO add your handling code here:
        // from the list remove the layer name and remove all objects associated with it
        
    }//GEN-LAST:event_DeleteLayerActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    private void AddLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLayerActionPerformed
// TODO add your handling code here:
        thingsToAddVisibility = !thingsToAddVisibility;
        ThingsToAdd.setVisible(thingsToAddVisibility);
    }//GEN-LAST:event_AddLayerActionPerformed

    private void LayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LayersActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_LayersActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });*/
        
        // Create the frame with the title
        Gui f = new Gui();
        f.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);

        // Add applet to the frame and display the frame.
        f.setSize (new Dimension (1024,768));
        f.setVisible (true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCrisis;
    private javax.swing.JButton AddEntry;
    private javax.swing.JButton AddLayer;
    private javax.swing.JButton AddObstacle;
    private javax.swing.JButton AddPeople;
    private javax.swing.JButton AddResource;
    private javax.swing.JMenuItem CloseScenario;
    private javax.swing.JButton DeleteLayer;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel LayerActions;
    private javax.swing.JList LayerList;
    private javax.swing.JPanel LayerPanel;
    private javax.swing.JMenu Layers;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JMenuItem LoadScenario;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem NewScenario;
    private javax.swing.JMenuItem SaveScenario;
    private javax.swing.JInternalFrame ThingsToAdd;
    private javax.swing.JPanel ThingsToAddPanel;
    private javax.swing.JMenu Tools;
    private javax.swing.JMenu View;
    private javax.swing.JMenu Window;
    private javax.swing.JTextArea temp;
    // End of variables declaration//GEN-END:variables
    
}
